function topMenu_load(){

  document.getElementById("topMenu").innerHTML = '<nav class="navbar border-bottom bg-dark fixed-top navbar-expand-lg"><div class="container-fluid"><a class="navbar-brand" href="#"><img src="https://bushel.truevine.online/source/BushelIconWordmark.svg" width="100px" alt=""></a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="navbarSupportedContent"><ul class="navbar-nav me-auto mb-2 mb-lg-0"><li class="nav-item"><a class="nav-link" aria-current="page" href="https://bushel.truevine.online/">Home</a></li><li class="nav-item"><a class="nav-link" href="https://github.com/True-Vine-Online/bushel/wiki">Documentation</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">More</a><ul class="dropdown-menu"><li><a class="dropdown-item" href="https://bushel.truevine.online/about.html">About</a></li><li><a class="dropdown-item" target="_blank" href="https://github.com/True-Vine-Online/bushel/issues/new">Contact</a></li><li><a class="dropdown-item" href="https://bushel.truevine.online/contentpolicies.html">Policies</a></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item" href="https://github.com/True-Vine-Online/bushel/issues/new" target="_blank">Report an issue</a></li></ul></li></ul><button class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#exampleModal">Search</button></div></div></nav><div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h1 class="modal-title fs-5" id="exampleModalLabel">Search Bushel</h1><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><center><embed src="https://bushel.truevine.online//source/search.html" width="70%" height="auto" style="overflow-y: auto;"></center></div><div class="modal-footer"><button type="button" class="btn btn-dark" data-bs-dismiss="modal">Close</button></div></div></div></div>'



}


function footMenu_load(){

  document.getElementById("footMenu").innerHTML = '<section width="100%" style="background-color:#1a1a1a; padding-top: 25px; padding-bottom: 25px;"><div class="container"><!-- Footer Content --><div class="container text-center"><div class="row align-items-start"><div class="col"><a href="https://github.com/True-Vine-Online/bushel/issues/new" target="_blank">Report</a></div><div class="col"><a href="https://github.com/True-Vine-Online/bushel/wiki" target="_blank">Documentation</a></div><div class="col"><a href="https://bushel.truevine.online/contentpolicies.html">Policies</a></div></div></div><center style="padding-top:15px"><p><b>Bushel</b> by <a target="_blank" href="https://truevineonline.com/">Truevine Online LLC</a></p><p>©2025 Truevine Online LLC</p></center></div></section>'

}
